"""fix_bug_2.0

Revision ID: 52c2de90aa4f
Revises: 3a7d9626cef9
Create Date: 2025-09-27 22:30:04.876029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c2de90aa4f'
down_revision: Union[str, None] = '3a7d9626cef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_last_name_key', 'user', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('user_last_name_key', 'user', ['last_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
